Feature/ownable contracts to owned
popcorndao/workspace pull request #103
Opened 2021-05-10 10:16 UTC by RedVeil

2021-05-10 22:21 UTC, anthonymartin requested changes

2021-05-12 12:08 UTC, RedVeil commented on packages/contracts/contracts/BeneficiaryVaults.sol
as per discussion Owned stays for now until we find a better solution

2021-05-12 12:32 UTC, RedVeil commented on packages/contracts/contracts/BeneficiaryRegistry.sol
> +contract BeneficiaryRegistry is IBeneficiaryRegistry, Owned {
created a Governed and CouncilControlled contract as abstraction

2021-05-12 12:35 UTC, RedVeil commented
@anthonymartin changes implemented, could you give me some feedback / your opinion about extracting Governed and CouncilControlled into extra contracts?

2021-05-17 11:44 UTC, anthonymartin approved these changes

2021-05-17 11:44 UTC, merged