Feature/pop staking rewards
popcorndao/workspace pull request #114
Opened 2021-05-14 14:52 UTC by RedVeil

2021-05-20 11:24 UTC, anthonymartin requested changes

2021-05-20 11:24 UTC, anthonymartin commented on packages/contracts/contracts/Staking.sol
> +  function notifyRewardAmount(uint256 reward)
this function should be callable by Owner and by RewardsManager as well. We'll need to update the RewardsManager contract to call this function when the rewards distribution is made. We also want to have the flexibility to send rewards to this contract outside of the RewardsManager because we'll have minted POP to distribute via this contract

2021-05-21 16:10 UTC, mefuru commented on packages/contracts/contracts/Staking.sol
>    uint256 constant SECONDS_IN_A_WEEK = 604800;
see #115

2021-05-21 16:10 UTC, mefuru commented on packages/contracts/contracts/Staking.sol
> +  function getWithdrawableBalance() public view override returns (uint256) {
see #115

2021-05-21 16:10 UTC, mefuru commented on packages/contracts/contracts/Staking.sol
> +  uint256 constant MAX_LOCK_TIME = SECONDS_IN_A_WEEK * 52 * 4; // 4 years
see #115

2021-05-21 16:10 UTC, mefuru commented on packages/contracts/contracts/Staking.sol
> +    _totalLocked = _totalLocked.add(amount);
see #115

2021-05-21 16:10 UTC, mefuru commented on packages/contracts/contracts/Staking.sol
> +  function _addStakeToLocked(uint256 amount, uint256 lengthOfTime) internal {
see #115

2021-05-26 13:31 UTC, RedVeil commented on packages/contracts/contracts/Staking.sol
> +  function notifyRewardAmount(uint256 reward)
done in https://github.com/popcorndao/workspace/pull/151

2021-05-27 09:35 UTC, RedVeil commented on packages/contracts/contracts/Staking.sol
> +    uint256 _end;
added _blockLock in https://github.com/popcorndao/workspace/pull/115/commits/b6679c2c8ac92d5d3ad01003ee58f05fb184be34

2021-05-28 11:13 UTC, closed without merging