Feature/decaying voice credits
popcorndao/workspace pull request #115
Opened 2021-05-17 11:10 UTC by RedVeil

This implementation doesnt really decay voice credits but getVoiceCredits (which is used by the election contract to determine voice credit amounts) calculates and returns decayed voice credits. The decay here is calculated using seconds and updated per block.

The problem with this approach is that the frontend will display a slightly higher voice credit amount than the election contract will get a few seconds later when checking the submitted amount.

2021-05-20 10:03 UTC, anthonymartin requested changes

2021-05-20 10:03 UTC, anthonymartin commented on packages/contracts/test/Staking.test.js
> +      ).to.equal("9999999999999676800");
can you use parseEther for better readability in these tests?

2021-05-20 10:03 UTC, anthonymartin commented on packages/contracts/test/Staking.test.js
> +  describe("getVoiceCredits", function () {
we should have more comprehensive tests that demonstrate voice credits at different scales and lock up periods. We should also write tests that demonstrate the decaying effect at different scales.

2021-05-21 16:09 UTC, mefuru commented
Resolved issues from #114 such as renaming staking functions, passing address to getwithdrawable balance, using globally available time variables from solidity

2021-05-31 16:31 UTC, anthonymartin approved these changes
Looks good. I’ve left some comments that can be addressed in  another PR so we can merge this one.

2021-05-31 16:31 UTC, anthonymartin commented on packages/contracts/test/Staking.test.js
> +      ethers.provider.send("evm_increaseTime", [700000]);
It might be a little clearer here if the time increased was a variable so it’s understood how long it is fast forwarding

2021-05-31 16:31 UTC, anthonymartin commented on packages/contracts/test/Staking.test.js
> +      //Dont know how to test this. RewardPerToken2 is higher than 1 even though they both earn less than if only one person was staking
Not sure what you mean here. However, to test this the test could set a defined rewards period with a set staked amount by one address, and at the end of the rewards period it could check the amount earned. Then another rewards period can be initialized for the same period of time with the same reward amount but with 2 addresses staking the amount. It would be expected that the amount earned would be half on the second reward period, right?

2021-05-31 16:35 UTC, merged