BNP contract
popcorndao/workspace pull request #136
Opened 2021-05-25 09:03 UTC by saharAP

2021-05-25 23:23 UTC, anthonymartin requested changes

2021-05-25 23:23 UTC, anthonymartin commented on packages/contracts/test/BeneficiaryNomination.test.js
> +      await this.BNPContract.connect(voter5).vote(PROPOSALID,Vote.No);
can you modify this test to ensure that the voting does not become finalized as soon as more no votes are counted than yes votes during the challenge period? That should only happen on the first count

2021-05-26 00:35 UTC, anthonymartin commented
@saharAP - I've made some updates myself on https://github.com/popcorndao/workspace/tree/feature/beneficiary-proposals - can you merge those changes into this branch and take a look at the issues that haven't been resolved yet?

2021-05-26 11:16 UTC, saharAP commented on packages/contracts/contracts/BeneficiaryRegistry.sol
> +    override
I added addBeneficiary and revokeBeneficiary functions into the IBeneficiaryRegistry, so if I don't use the override keyword, I will get this error: "TypeError: Overriding function is missing "override" specifier"

2021-05-27 19:42 UTC, anthonymartin commented on packages/contracts/contracts/BeneficiaryNomination.sol
> -      require(
why was this removed? it should be required because yes votes are only allowed when `ProposalStatus.New`

2021-06-14 01:45 UTC, merged