Feature/beneficiary nomination form
popcorndao/workspace pull request #160
Opened 2021-06-03 15:46 UTC by mefuru

Addresses issues #111 and #141

To see the form in action click Proposals > Propose new beneficiary from nav bar

Bear in mind that, images and reports are uploaded to IPFS before we ask for POP tokens to be locked.

2021-06-03 15:57 UTC, RedVeil commented on packages/app/components/Beneficiary-Proposals/Form-Pages/IpfsUpload.tsx
> +                <svg
Swap this out with an hero-icon or similar

2021-06-03 16:10 UTC, RedVeil commented on packages/app/components/Beneficiary-Proposals/Form-Pages/Intro.tsx
> +            <div className="mt-3 sm:mt-0 sm:ml-3">
should always have cursor-pointer including the test on it

2021-06-03 16:32 UTC, RedVeil commented
a bunch of maps dont have unique key props. its advised to add them for performance reasons but also cause it can cause janky behavior at times

2021-06-03 16:35 UTC, RedVeil commented
Please redirect us for now after submission to the landing page or proposals so its clear for the user that the submission was successful.

(with full ipfs and contract integration one would redirect to the finished proposal)

2021-06-03 16:45 UTC, RedVeil commented on packages/app/components/Beneficiary-Proposals/Form-Pages/EthereumAddress.tsx
> +  if (currentStep === 2) {
i think this conditional should be handled by the container-component rendering all steps

2021-06-03 16:47 UTC, RedVeil commented on packages/app/components/Beneficiary-Proposals/Form-Pages/LandingPage.tsx
> +export default function LandingPage(): JSX.Element {
could you rename this to PropsalForm or similar?

2021-06-03 16:55 UTC, RedVeil commented
On the proposal preview: Could you get rid of the voting section and instead show a big submission button again?
I think the preview of how voting looks like is not important here but the submission button on top of the page could be difficult to find for some.
Maybe a second submission button could also be floating, just smth to make it more noticable.

2021-06-03 17:05 UTC, RedVeil commented
add some edit/back button as secondary button next to "submit" to allow people to easily go back in the form and change informations

2021-06-03 20:38 UTC, anthonymartin commented
@mefuru the build is failing - could you look into that?

2021-06-03 21:45 UTC, anthonymartin commented on packages/app/components/Beneficiary-Proposals/Form-Pages/ProofOfOwnership.tsx
> +                id="poo"
this has to be the worst acronym ever haha

2021-06-10 11:11 UTC, RedVeil approved these changes

2021-06-11 06:59 UTC, anthonymartin requested changes

2021-06-11 06:59 UTC, anthonymartin commented on packages/app/components/Beneficiary-Proposals/Form/ProposalForm.tsx
> +    additionalImages: [],
this default form is defined in several places:

https://github.com/popcorndao/workspace/pull/160/files#diff-688a8af461b89da8cb563bf1794fab0c1486da5fae86416a838be0d5d21c693cR54
https://github.com/popcorndao/workspace/pull/160/files#diff-474246307370b1d3f21aa7b8d383eef4cccf6fb6dc2f82d97b0004cc0deaec5bR59

instead of rewriting it in each place its used, a canonical defaultForm var could be used which is exported from this file

2021-06-11 06:59 UTC, anthonymartin commented on packages/app/components/Beneficiary-Proposals/Form/ProposalForm.tsx
> +        form={form}
it would be cleaner to pass the tuple `form={[form, setForm]}` and destructure it from each component

2021-06-11 06:59 UTC, anthonymartin commented on packages/app/package.json
> +    "next": "^10.0.0",
why change from latest?

2021-06-11 06:59 UTC, anthonymartin commented on packages/app/package.json
> +    "use-local-storage-state": "^10.0.0",
can this be removed?

2021-06-11 06:59 UTC, anthonymartin commented on packages/contracts/scripts/deployWithValues.ts
> +        .stake(utils.parseEther("1000"), 86400 * 365 * 4);
why are there changes to this file?

2021-06-11 06:59 UTC, anthonymartin commented on packages/app/interfaces/beneficiaries.tsx
>    dribbleUrl?: string;
can we get rid of dribble? that's not needed

2021-06-11 06:59 UTC, anthonymartin commented on packages/app/components/Beneficiary-Proposals/Form/IpfsUpload.tsx
> +const baseStyle = {
was no tailwind ui element  available to be used here?

2021-06-11 06:59 UTC, anthonymartin commented on packages/app/components/Beneficiary-Proposals/Form/Preview.tsx
> +        setTimeout(() => (window.location.href = '/'), 3000);
`router.push` should be used instead otherwise browsing history will be lost

2021-06-11 11:57 UTC, mefuru commented on packages/app/package.json
> +    "next": "^10.0.0",
this change is a remnant of next.js build issue fix investigation, will remove

2021-06-11 11:58 UTC, mefuru commented on packages/app/package.json
> +    "use-local-storage-state": "^10.0.0",
yup

2021-06-11 12:03 UTC, mefuru commented on packages/app/interfaces/beneficiaries.tsx
>    dribbleUrl?: string;
done

2021-06-11 13:38 UTC, mefuru commented on packages/app/components/Beneficiary-Proposals/Form/IpfsUpload.tsx
> +const baseStyle = {
we are using a tailwindui component but it uses an svg for its icon so i swapped it out for an hero icon. but now i've swapped out the hero icons for feather which look more similar to the svg icon used in the tailwindui component

2021-06-11 13:51 UTC, mefuru commented on packages/contracts/scripts/deployWithValues.ts
> +        .stake(utils.parseEther("1000"), 86400 * 365 * 4);
due to a change in the stake contract to increase precision. this change should be made in other branches, too

2021-06-14 02:00 UTC, anthonymartin approved these changes

2021-06-14 02:00 UTC, merged