Feature/beneficiary takedown grid
popcorndao/workspace pull request #166
Opened 2021-06-10 10:17 UTC by mefuru

Addresses #118 

Add a takedown grid at /beneficiary-proposals/takedowns/all

Update child components to handle takedown data, such as cards and proposal/takedown stage pop up content

2021-06-15 10:59 UTC, RedVeil approved these changes

2021-06-16 18:26 UTC, anthonymartin requested changes

2021-06-16 18:26 UTC, anthonymartin commented on packages/app/pages/beneficiary-proposals/[id].tsx
> +  //Where does this proposal get stored?
this should be passed down to the child component right?

2021-06-16 18:26 UTC, anthonymartin commented on packages/app/interfaces/beneficiaries.tsx
> +export enum Status {
turns out it's not needed to set =0, =1, etc. it should be handled in that way automatically

2021-06-16 20:06 UTC, mefuru commented on packages/app/pages/beneficiary-proposals/[id].tsx
> +  //Where does this proposal get stored?
yup, it should. amended to pass it down. possibly corrected/addressed in another pr

2021-06-16 20:16 UTC, anthonymartin approved these changes

2021-06-16 20:16 UTC, merged