Feature/reward voting
popcorndao/workspace pull request #172
Opened 2021-06-14 06:50 UTC by RedVeil

RewardParticipation contract to award POP for participating in GrantElections or Beneficiary Proposals and Takedowns

2021-06-14 14:47 UTC, anthonymartin requested changes
looking good. nice job

2021-06-14 14:47 UTC, anthonymartin commented on packages/contracts/contracts/RewardParticipation.sol
> +      "not enough funds for vault"
in case the contract doesn't hold a large enough balance, the governance process should continue without reverting so this should return without failing

2021-06-14 14:47 UTC, anthonymartin commented on packages/contracts/contracts/RewardParticipation.sol
> +  enum VaultStatus {INIT, OPEN}
nit: the enum values don't need to be all caps

2021-06-14 14:47 UTC, anthonymartin commented on packages/contracts/contracts/RewardParticipation.sol
> +pragma solidity >=0.7.0 <0.8.0;
should we include a notifyRewardsAmount function similar to the other rewards function? The contracts that implement this one may hold funds for other purposes so there should be a balance kept of tokens available specifically for participation rewards

2021-06-14 14:47 UTC, anthonymartin commented on packages/contracts/contracts/RewardParticipation.sol
> +contract RewardParticipation is Governed, ReentrancyGuard {
`ParticipationReward` would read more idiomatically

2021-06-14 14:47 UTC, anthonymartin commented on packages/contracts/contracts/RewardParticipation.sol
> +  function claimRewards() external nonReentrant {
this loop is probably ok in practice, but to avoid it, should we include a claimReward() function that receives a vaultId as an input?

2021-06-14 14:47 UTC, anthonymartin commented on packages/contracts/contracts/RewardParticipation.sol
> +    totalVaultedBalance = totalVaultedBalance.add(rewardBudget);
a balance would typically designate the realized amount that's present. perhaps `totalVaultsBudget` would be better. balance could be introduced as part of the `notifyRewardsAmount` function

2021-06-15 07:38 UTC, RedVeil commented on packages/contracts/contracts/RewardParticipation.sol
> +pragma solidity >=0.7.0 <0.8.0;
SetRewardsBudget sets the rewardsDefault for each vault. All new vaults get initalized with this rewardsBudget.
I now also added contributeToRewardBalance which takes an amount of POP transfers it to this contract and adds it to rewardBalance. RewardBalance gets updated everytime this function gets called or if someone claims their rewards.

2021-06-15 07:44 UTC, RedVeil commented on packages/contracts/contracts/RewardParticipation.sol
> +  function claimRewards() external nonReentrant {
My issue here is that we dont really have the ids of individual vaults. so one would need to get the array of vaultIds anyways and i dont see a reason to than only claim one of the vaults and not all of them.
Additionally i delete all vaults but with an individual claims i dont would need to delete entries in an array and either shift the whole array or have empty entries in the array. Both doesnt sound too great. I could also not delete the item but that would leave useless data and would add more computation to the claimRewards function as it has to loop through already empty entries.

2021-06-15 07:49 UTC, RedVeil commented on packages/contracts/contracts/RewardParticipation.sol
> +pragma solidity >=0.7.0 <0.8.0;
So setRewardsBudget is for setting the default RewardBudget and contributeRewardBalance for providing the token for the rewards

2021-06-21 21:09 UTC, anthonymartin commented on packages/contracts/contracts/ParticipationReward.sol
> +      index = numEntries.sub(21);
if `numEntries = 24`, `then index=3` ? not sure I understand this logic here

2021-06-21 21:09 UTC, anthonymartin commented on packages/contracts/contracts/ParticipationReward.sol
> +    for (uint256 i = 0; i < numEntries; i++) {
what if bounded the for loop to some number like 10 or numEntries (whichever is smaller)? could we remove the subsequent function then?

2021-06-22 13:04 UTC, RedVeil commented on packages/contracts/contracts/ParticipationReward.sol
> +      index = numEntries.sub(21);
I changed it in https://github.com/popcorndao/workspace/pull/172/commits/e37271a90230211931fccb3aba21f5bb7364c0e1 to go in reverse order. (I wasnt sure if delete on a loop that counts upwards might lead to some weird behavior)

The idea in the new commit is to calculate a stop. Every item with a higher index than the stop should get claimed and deleted. Its sub 21 since it takes the array length. If we have an array of 24 entries and we want the last 20 the stop would be index 3, so everything above it gets claimed (20 items) leaving 4 items in the array.

2021-06-22 13:07 UTC, RedVeil commented on packages/contracts/contracts/ParticipationReward.sol
> +    for (uint256 i = 0; i < numEntries; i++) {
We could do the opposite and remove claimRewards since we have claimLatestRewards. The issue of claimRewards is that it deleted the whole rewards array of this user, so if we claim less than they have we still delete their claim. ClaimLatestRewards deleted per item

2021-07-08 23:15 UTC, anthonymartin approved these changes

2021-07-09 00:00 UTC, merged

2021-07-09 00:12 UTC, anthonymartin commented
@RedVeil - I accidentally merged this not realizing the tests were failing. Can you fix them please so we can merge this?