Feature/single responsibility
popcorndao/workspace pull request #190
Opened 2021-06-21 11:54 UTC by mefuru

Addresses #187 

Add separate beneficiary and proposal interfaces, move proposal components out of beneficiary directory into their own directory, add common components directory for components used in bennies and proposals plus other small changes

2021-06-21 20:48 UTC, anthonymartin commented on packages/app/components/Beneficiaries/BeneficiaryCard.tsx
> +  displayData: BaseBeneficiary;
should we call this property a beneficiary?
e.g.
`beneficiary: Beneficiary`

2021-06-21 20:48 UTC, anthonymartin commented on packages/app/components/Beneficiaries/BeneficiaryCard.tsx
> +  electionProps: ElectionProps;
could this be ElectionMetadata directly? it seems there's more nesting than required?

e.g.
`election: ElectionMetadata`

2021-06-21 20:48 UTC, anthonymartin commented on packages/app/components/Beneficiaries/BeneficiaryCard.tsx
> +        <GrantSlider displayData={displayData} electionProps={electionProps} />
similarly, it would be more expressive/readable if displayData was more concrete: 
e.g. 
`beneficiary={beneficiary}`

2021-06-21 20:48 UTC, anthonymartin commented on packages/app/components/Beneficiaries/BeneficiaryGrid.tsx
> +  cardProps: BaseBeneficiary[];
could this be called `beneficiaries`? it's more concrete and closer to the actual data that's being passed here

2021-06-21 20:48 UTC, anthonymartin commented on packages/app/components/Beneficiaries/BeneficiaryPage.tsx
>    displayData: Beneficiary | BeneficiaryProposal;
I thought this was to be one of the changes so that the interface would be specific to either a beneficiary or a proposal?

2021-06-21 20:48 UTC, anthonymartin commented on packages/app/components/Proposals/ProposalCard.tsx
> +  displayData: BaseProposal;
could this property be called proposal?

and does the interface need `Base` in the name? could it not also be named proposal?

e.g.

`proposal: Proposal;`

2021-06-21 20:48 UTC, anthonymartin commented on packages/app/components/Proposals/ProposalCard.tsx
> +  isProposal?: boolean;
since all are proposals should this property name be changed? or replace `isProposal` & `isTakedown` with a `proposalType` property?

2021-06-21 20:48 UTC, anthonymartin commented on packages/app/interfaces/proposals.tsx
> +export interface BeneficiaryProposal extends BaseProposal {
why not combine these interfaces into a Proposal interface?

2021-06-22 09:50 UTC, mefuru commented on packages/app/components/Beneficiaries/BeneficiaryCard.tsx
> +  electionProps: ElectionProps;
One of the the child components (VoteSlider) uses data not in the ElectionMetadata, hence the need for nesting

2021-06-23 04:07 UTC, anthonymartin commented on packages/app/components/Beneficiaries/BeneficiaryPage.tsx
>    displayData: Beneficiary | BeneficiaryProposal;
@mefuru ?

2021-06-23 04:27 UTC, anthonymartin requested changes

2021-06-23 04:27 UTC, anthonymartin commented on packages/app/components/Proposals/ProposalGrid.tsx
> +                    title === 'Eligible Beneficiaries' ? (
there should be a switch on a type/enum here, not on a text string since these are likely to change

2021-06-23 04:27 UTC, anthonymartin commented on packages/app/utils/getProposals.ts
> +// From typechain output
why reproduce typechain interfaces here?

2021-06-23 04:27 UTC, anthonymartin commented on packages/app/components/Beneficiaries/BeneficiaryPage.tsx
>    displayData: Beneficiary | BeneficiaryProposal;
<img width="783" alt="Screen Shot 2021-06-23 at 12 22 18 AM" src="https://user-images.githubusercontent.com/949506/123035284-63331700-d3eb-11eb-84f3-1ee2bb0746bd.png">

There are typescript errors because of this union type interface. The screenshot above shows the way to solve the error. alternatively this could be used for the components where the exact interface is known

`  const beneficiary = displayData as Beneficiary;`

2021-06-23 04:27 UTC, anthonymartin commented on packages/app/components/Beneficiaries/BeneficiaryPage.tsx
>    displayData: Beneficiary | BeneficiaryProposal;
if the union type can be avoided it should. nonetheless, all typescript errors should be resolved

2021-06-23 05:04 UTC, anthonymartin commented
`packages/app/interfaces/proposals.tsx` and  `packages/app/interfaces/beneficiaries.tsx` have duplicate interfaces defined. only only interface for beneficiary application should be used to remove duplication and avoid bugs when updating one interface

2021-06-23 10:56 UTC, mefuru commented on packages/app/components/Beneficiaries/BeneficiaryPage.tsx
>    displayData: Beneficiary | BeneficiaryProposal;
only the components used by both the proposal and beneficiary pages have union types. And i don't see TS errors my end.

2021-06-23 11:15 UTC, mefuru commented on packages/app/utils/getProposals.ts
> +// From typechain output
In order to specify the proposal type we pass to the addIpfsDataToProposal

![image](https://user-images.githubusercontent.com/3315297/123087018-fbe18b00-d41b-11eb-9a45-b5bbe8641d6e.png)

couldn't think of any other way to get autocomplete working in addIpfsDataToProposal. any suggestions?

2021-06-23 13:22 UTC, mefuru commented on packages/app/components/Beneficiaries/BeneficiaryPage.tsx
>    displayData: Beneficiary | BeneficiaryProposal;
the issue with union types will be addressed w/ the nested proposal-beneficiary application interfaces

2021-06-25 18:07 UTC, anthonymartin commented on packages/app/utils/ProposalAdapter.ts
> +export const ProposalAdapter = (
Should be called BeneficiaryGovernanceAdapter, since it's an adapter for the BeneficiaryGovernance contract?

2021-06-25 18:07 UTC, anthonymartin commented on packages/app/utils/addIpfsDataToProposal.ts
> +  proposal,
type?

2021-06-25 18:07 UTC, anthonymartin commented on packages/app/utils/formatBigNumber.ts
> +  if (BigNumber.isBigNumber(value)) {
ideally utils should live in @popcorn/utils package for reusability

2021-06-28 12:20 UTC, mefuru commented on packages/app/pages/beneficiary-proposals/takedowns/index.tsx
> +      ProposalAdapter(contracts.beneficiaryGovernance, IpfsClient)
it should. unsure what the issue is. due to refactoring, the above code will now be found in components/Proposals/ProposalsGrid.tsx

2021-06-28 12:33 UTC, mefuru commented on packages/app/utils/addIpfsDataToProposal.ts
> +  proposal,
type added.

we now source the proposal type from the function signature of the BeneficiaryGovernance contract from the web3 context which sources its type definitions from a typechain typescript definition file. see BeneficiaryGovernanceAdapter

2021-06-28 12:34 UTC, mefuru commented on packages/app/utils/getProposals.ts
> +// From typechain output
see comment below

2021-06-28 19:20 UTC, anthonymartin approved these changes

2021-06-28 19:20 UTC, merged