Sketch out rewards contract
popcorndao/workspace pull request #2
Opened 2021-02-24 16:40 UTC by partywave

2021-02-24 18:45 UTC, anthonymartin requested changes
looking good

2021-02-24 18:45 UTC, anthonymartin commented on packages/contracts/contracts/RewardsManager.sol
> +  function _distribute(uint256 amount_) internal {
should we have vaults for the treasury as well as the DAO?

Governance should also be able to define a split between the 3 kinds of vaults:
treasury, DAO, and bennies. we can set the default to 33/33/34

2021-02-24 18:45 UTC, anthonymartin commented on packages/contracts/contracts/RewardsManager.sol
> +    require(vaults[vaultId_].status == VaultStatus.Open, "Vault must be open");
missing endBlock check

2021-02-24 18:46 UTC, partywave commented on packages/contracts/contracts/RewardsManager.sol
> +
I'll add a @todo. The BeneficiaryRegistry needs an interface so it can do this check otherwise it will have to import that whole contract which will be gas costly.

2021-02-24 18:49 UTC, partywave commented on packages/contracts/contracts/RewardsManager.sol
> +  function _distribute(uint256 amount_) internal {
not sure i understand this, probably needs a seperate conversation.

2021-02-26 23:13 UTC, anthonymartin approved these changes
nice job 🙌

2021-02-26 23:14 UTC, anthonymartin commented on packages/contracts/contracts/RewardsManager.sol
> +  function _distribute(uint256 amount_) internal {
https://github.com/popcorndao/workspace/issues/6

2021-02-26 23:15 UTC, merged