Feature/regions
popcorndao/workspace pull request #213
Opened 2021-07-06 08:11 UTC by RedVeil

Added support for regions in contracts. Beneficiary-Proposals and Beneficiaries have a region parameter and Elections now are mapped to certain regions controlled by individual councils.

The Region contract stores all created regions. Councils are created per region. Any contract that needs to check regions needs to interact with the region-contract to query the existing regions.

2021-07-06 08:12 UTC, RedVeil commented
This does not yet contain the separations of nominations and takedowns in beneficiaryGovernance

2021-07-21 15:20 UTC, anthonymartin requested changes
should this be re-targeted to the grant elections refactor branch?

2021-07-21 15:20 UTC, anthonymartin commented on packages/contracts/contracts/BeneficiaryVaults.sol
this contract could be simplified significantly if only one contract is created/deployed per region as part of `Region.addRegion()`. The RewardsManager would simply iterate over the regions and send the rewards to each contract. This would avoid having to update the code in BeneficiaryVaults

2021-07-26 07:31 UTC, RedVeil commented on packages/contracts/contracts/BeneficiaryRegistry.sol
> +      msg.sender == owner() ||
i was thinking that maybe a region has caused issues or violated some guidelines of the community there is no way to remove them as they would need to remove themself. But this way the owner has quite a bit of power (which could be resolved by a multisig)

2021-07-26 07:34 UTC, RedVeil commented on packages/contracts/contracts/BeneficiaryVaults.sol
You mean we deploy beneficiaryVaults once per region? This would mean we need to save the address of each of those contracts in the region contract correct?

2021-07-26 13:48 UTC, anthonymartin commented on packages/contracts/contracts/BeneficiaryVaults.sol
@RedVeil yes that's right

2021-07-26 13:49 UTC, anthonymartin commented on packages/contracts/contracts/BeneficiaryRegistry.sol
> +      msg.sender == owner() ||
ok got it

2021-08-03 23:38 UTC, anthonymartin approved these changes

2021-08-03 23:38 UTC, anthonymartin commented on packages/contracts/contracts/GrantElections.sol
> +      election.electionState != ElectionState.Finalized,
this require could be removed because the one below should be sufficient

2021-08-04 00:02 UTC, anthonymartin commented
@RedVeil the tests are failing on this branch, can you fix that?

```
  1 failing

  1) GrantElections
       voting
         should vote successfully:

      AssertionError: expected [ Array(1) ] to deeply equal [ Array(1) ]
      + expected - actual


      at Context.<anonymous> (test/GrantElections.test.ts:589:41)
      at step (test/GrantElections.test.ts:33:23)
      at Object.next (test/GrantElections.test.ts:14:53)
      at fulfilled (test/GrantElections.test.ts:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at runNextTicks (internal/process/task_queues.js:66:3)
      at listOnTimeout (internal/timers.js:518:9)
      at processTimers (internal/timers.js:492:7)
      ```

2021-08-05 13:24 UTC, anthonymartin approved these changes

2021-08-05 15:17 UTC, anthonymartin approved these changes

2021-08-05 15:17 UTC, merged