Feature/frontend rewards manager
popcorndao/workspace pull request #215
Opened 2021-07-07 13:20 UTC by RedVeil

frontend for rewardsManager to swap 3crv into pop and distribute rewards

2021-07-09 21:29 UTC, ecmendenhall approved these changes
Looks good! I appreciate the BigNumber rounding helpers.

2021-07-12 01:21 UTC, anthonymartin requested changes

2021-07-12 01:21 UTC, anthonymartin commented on packages/contracts/test/Integration.test.ts
> +describe.only("Integration", function () {
should remove only from here

2021-07-12 01:21 UTC, anthonymartin commented on packages/app/next.config.js
> +    ADDR_BENEFICIARY_VAULT:process.env.ADDR_BENEFICIARY_VAULT,
these new env vars should be added to `.env.example`

2021-07-12 01:21 UTC, anthonymartin commented on packages/app/package.json
> +    "prettier-plugin-organize-imports": "^2.2.0",
nice

2021-07-12 01:21 UTC, anthonymartin commented on packages/app/pages/rewards-manager/index.tsx
> +      contracts.threeCrv
is 3crv hardcoded here for a reason? we'll want to make the interface so that we're able to view and transfer any arbitrary token that the contract holds

2021-07-12 01:21 UTC, anthonymartin commented on packages/contracts/package.json
> -    "postinstall": "yarn compile",
why is this removed?

2021-07-12 09:13 UTC, RedVeil commented on packages/contracts/package.json
> -    "postinstall": "yarn compile",
its back in, was testing smth and forgot about it. thanks for the reminder

2021-07-12 09:31 UTC, RedVeil commented on packages/app/pages/rewards-manager/index.tsx
> +      contracts.threeCrv
Currently we use only 3crv in the rewardsManager. Once we add more token we would need some kind of registry, either hardcoded in the frontend or somewhere saved in the rewardsManager about which token we are using. SInce i dont know how this will be implemented i decided to only support 3crv right now and add the rest later once we know how the implementation will look like

2021-07-22 06:18 UTC, RedVeil commented
@anthonymartin Good call targeting develop-beneficiary-governance. :)

2021-07-26 14:36 UTC, anthonymartin approved these changes

2021-07-26 14:43 UTC, merged