Feature/beneficiary image descriptions
popcorndao/workspace pull request #219
Opened 2021-07-08 13:31 UTC by RedVeil

2021-07-08 18:33 UTC, anthonymartin requested changes

2021-07-08 18:33 UTC, anthonymartin commented on packages/app/components/Proposals/Form/ControlledTextInput.tsx
> +  updateInput?: (value: string) => void;
the interface here is a bit more complicated than it was before.

the interface would be simplified if the `updateInput` argument  was modified like this:
```
updateInput: (value: string | {value: string, index: number }) => void;
```
then the inputIndex and updateIndexedInput could be removed altogether

2021-07-08 18:33 UTC, anthonymartin commented on packages/app/components/Proposals/Form/IpfsUpload.tsx
> +  setLocalStateMultiple?: (input: string[]) => void;
the extra `setLocalStateMultiple` prop could be avoided by updating the setLocalState prop as:

`setLocalState: (input: string | string[]) => void;`

2021-07-09 07:50 UTC, RedVeil commented on packages/app/components/Proposals/Form/IpfsUpload.tsx
> +  setLocalStateMultiple?: (input: string[]) => void;
thats great! didnt know you could do this

2021-07-09 08:01 UTC, RedVeil commented on packages/app/components/Proposals/Form/ControlledTextInput.tsx
> +  updateInput?: (value: string) => void;
i set the index parameter of the function to optional and it worked. But dont i still need the inputIndex?

2021-07-12 04:04 UTC, anthonymartin approved these changes

2021-07-12 12:02 UTC, mefuru approved these changes

2021-07-12 12:02 UTC, merged