Feature/batch hysi interaction
popcorndao/workspace pull request #265
Opened 2021-07-16 15:14 UTC by RedVeil

2021-07-16 16:25 UTC, anthonymartin commented on packages/contracts/contracts/BatchSetInteraction.sol
> +    batch.claimable = 1;
should `bool` be used here?

2021-07-16 16:25 UTC, anthonymartin commented on packages/contracts/contracts/BatchSetInteraction.sol
> +  CurveAddressProvider public curveAddressProvider;
this var is unused. should it be?

2021-07-16 16:25 UTC, anthonymartin commented on packages/contracts/contracts/BatchSetInteraction.sol
> +      MintBatch storage batch = mintBatches[currentBatchId];
if we convert the redeemed tokens to CRV then only one struct could be used I think, right?

2021-07-16 16:25 UTC, anthonymartin commented
other topic to be discussed: deposit & stake

2021-07-16 16:46 UTC, anthonymartin commented on packages/contracts/contracts/BatchSetInteraction.sol
> +    setBasicIssuanceModule.issue(setToken, amount_, address(this));
should there be some calculation to determine the amount of sets to mint based on the contracts balance of the components or will that happen on the keeper side?

2021-07-22 08:50 UTC, RedVeil commented on packages/contracts/contracts/BatchSetInteraction.sol
> +    batch.claimable = 1;
i mean bool works technically better but costs a bit more gas, which might be an unnecessary optimization at this stage

2021-07-22 08:54 UTC, RedVeil commented on packages/contracts/contracts/BatchSetInteraction.sol
> +      MintBatch storage batch = mintBatches[currentBatchId];
yes, that would make things much easier.

2021-07-22 08:55 UTC, RedVeil commented on packages/contracts/contracts/BatchSetInteraction.sol
> +    setBasicIssuanceModule.redeem(setToken, batch.suppliedToken, address(this));
I might have missed it but didnt see it in the ticket. It makes absolutely sense though and as you said eliminates the need for two distinct structs

2021-07-22 08:56 UTC, RedVeil commented on packages/contracts/contracts/BatchSetInteraction.sol
> +    setBasicIssuanceModule.issue(setToken, amount_, address(this));
I was thinking on the keeper side cause it takes some work of but otherwise we could ask the issuanceModule what the underlying amounts are for one token and than divide our balance by this to arrive at the mintable/redeemable amount

2021-08-04 00:49 UTC, anthonymartin requested changes

2021-08-04 00:49 UTC, anthonymartin commented on packages/contracts/contracts/BatchSetInteraction.sol
> +  function _claim(
this function does not seem to be called. should it be removed?

2021-08-04 00:49 UTC, anthonymartin commented on packages/contracts/contracts/BatchSetInteraction.sol
> +    require(shares <= batch.unclaimedShares, "claiming too many shares");
ah the dreaded, "insufficient balance"

2021-08-04 00:49 UTC, anthonymartin commented on packages/contracts/contracts/BatchSetInteraction.sol
> +      .mul(underlyingToken[i].allocation)
the allocation should be derived programmatically and not statically using the function here: https://github.com/SetProtocol/set-protocol-v2/blob/master/contracts/protocol/modules/BasicIssuanceModule.sol#L203. see how the target amount of curveLP tokens is calculated here: https://github.com/popcorndao/workspace/blob/develop/packages/contracts/lib/SetToken/SetTokenCreator.ts#L52

2021-08-04 00:49 UTC, anthonymartin commented on packages/contracts/contracts/BatchSetInteraction.sol
> +    setBasicIssuanceModule.issue(setToken, amount_, address(this));
it makes sense to keep these calculations in the contract. it's possible that the calculations would be off if a large deposit transaction is mined while batchMint function transaction is being submitted. see my comments above

2021-08-04 00:49 UTC, anthonymartin commented on packages/contracts/test/BatchSetInteraction.test.ts
> +import { SignerWithAddress } from "@nomiclabs/hardhat-ethers/signers";
Can you create a network fork test?

2021-08-06 07:20 UTC, RedVeil commented on packages/contracts/contracts/BatchSetInteraction.sol
> +  function _claim(
absolutely :)

2021-08-06 07:20 UTC, RedVeil commented on packages/contracts/contracts/BatchSetInteraction.sol
> +    require(shares <= batch.unclaimedShares, "claiming too many shares");
what do you mean?

2021-08-12 13:03 UTC, anthonymartin commented on packages/contracts/contracts/BatchSetInteraction.sol
> +  function batchMint(uint256 amount_) external {
should also include `min_mint_amount`

2021-08-23 08:17 UTC, RedVeil commented
Ok the contract works now but im certainly not happy with it.
Since we have a lot of multiplications of BigNumbers i need to divide them again to prevent overflow. This leads to some inprecise caulculations which fluctate slightly. Therefore this introduces 3 failing tests in the network test and 2 in the normal test in which the expected value changes between 2 possible outcomes. This differences are only in the gwei amounts but means that the tests are not deterministic anymore.
It also means that i need to mint 0.3% less hysi than we could with a more precise calculation. 

If someone has an idea how to multiply a bunch of bigNumbers without any loss of accuracy id be happy to change this as it would hopefully eliminate these non deterministic tests and make the contract cleaner.

(I did check the BMI implementation but they dont do any of these calculations in the contract which is why i couldnt take their approach)

2021-08-23 08:18 UTC, RedVeil commented on packages/contracts/contracts/HysiBatchInteraction.sol
> +      uint256 yTokenIn3Crv = yTokenInCrvToken.mul(crvTokenIn3Crv).div(1e18);
This needs to be divided by 1e18 as it would lead to an overflow in the next calculation

2021-08-23 08:18 UTC, RedVeil commented on packages/contracts/contracts/HysiBatchInteraction.sol
> +      uint256 quantityIn3Crv = yTokenIn3Crv.mul(quantities[i]).div(1e18);
This needs to be divided by 1e18 as it would lead to an overflow in later calculations

2021-08-23 08:20 UTC, RedVeil commented on packages/contracts/contracts/HysiBatchInteraction.sol
> +      .mul(997)
Without taking 0.3% off here the sum of poolAllocations would be slightly larger than deposit 3crv. This happens due to the 2 divisions we make in earlier calculations which are again needed to prevent overflows.

2021-08-23 08:22 UTC, RedVeil commented on packages/contracts/test/HysiBatchInteraction.test.ts
> +            .withArgs(parseEther("99.7"));
This test changes between 99.7e and 99.6003e which comes from our divisions and rounding in the minting process.

2021-08-23 08:22 UTC, RedVeil commented on packages/contracts/test/HysiBatchInteraction.test.ts
> +        ).to.equal(parseEther("99.7"));
This test changes between 99.7e and 99.6003e which comes from our divisions and rounding in the minting process.

2021-08-23 08:23 UTC, RedVeil commented on packages/contracts/test/fork/BatchHysi.test.ts
> +            .withArgs(parseEther("0.406531836734693875"));
This test changes between 0.406531836734693875e and 0.406938775510204080e which comes from our divisions and rounding in the minting process.

2021-08-31 14:59 UTC, ecmendenhall requested changes
A few ideas, a few nitpicks, a few suggested changes. 

My only big blocker is double checking `batchRedeem` to make sure it's using the redemption-related parameters, like `lastRedeemedAt` in place of `lastMintedAt`.

2021-08-31 14:59 UTC, ecmendenhall commented on packages/contracts/contracts/Interfaces/Integrations/CurveContracts.sol
> +import "@openzeppelin/contracts/token/ERC20/SafeERC20.sol";
I like the convenience of using this file for a single import, but I'm wondering if it might be better to remove it and import these dependencies directly wherever they're used, so there is no chance of the interfaces getting out of sync.

2021-08-31 14:59 UTC, ecmendenhall commented on packages/contracts/test/HysiBatchInteraction.test.ts
> +});
Boring tests, but we should probably test the setters and their access controls as well in here for completeness.

2021-08-31 14:59 UTC, ecmendenhall commented on packages/contracts/test/fork/BatchHysi.test.ts
> +  //Deploy HysiBatchInteraction
This is a total nitpick, but these `getContractAt` calls are really "get" rather than "deploy," aren't they? The contracts are already deployed on the forked chain.

2021-08-31 14:59 UTC, ecmendenhall commented on packages/contracts/contracts/HysiBatchInteraction.sol
> +  function _setUnderlyingToken(Underlying[] memory underlying_) internal {
Would it be possible to store the current `underlying` on each `Batch` at the time the batch is created? We could then reset this array rather than appending to it. Each batch would then have a snapshot of the underlying components at the time it was created.

2021-09-01 07:47 UTC, RedVeil commented on packages/contracts/contracts/HysiBatchInteraction.sol
> +    //First is definitely easier to test but whats more valuable?
yeah we did that :) Dunno why my brain thought i could only do one

2021-09-01 07:47 UTC, RedVeil commented on packages/contracts/contracts/HysiBatchInteraction.sol
> +      (block.timestamp.sub(lastMintedAt) >= batchCooldown) ||
Could catch! Changed it

2021-09-01 07:49 UTC, RedVeil commented on packages/contracts/test/fork/BatchHysi.test.ts
> +  //Deploy HysiBatchInteraction
yup thats correct. maybe we should split the function that as we also deploy the batch-hysi contract

2021-09-02 00:18 UTC, anthonymartin commented on packages/contracts/contracts/HysiBatchInteraction.sol
> +  function _setUnderlyingToken(Underlying[] memory underlying_) internal {
good idea. included this in a ticket https://app.zenhub.com/workspaces/popcorn-603eb49d1a9a0b0011b49b36/issues/popcorndao/workspace/432

2021-09-12 19:01 UTC, merged