Feature/update beneficiary proposal fixtures
popcorndao/workspace pull request #325
Opened 2021-08-06 16:05 UTC by mefuru

Addresses #225 

Added fixtures for 20 beneficiary applications each with a unique name, mission statement/description, profile and header image.

The applications are used to create nomination and takedown proposals in all possible states, open period, challenge period, passed or failed.

The applications have also been registered for grant elections for all three grant phases. The quarterly election is closed, the yearly active and monthly is open for registration.

2021-08-06 16:38 UTC, anthonymartin requested changes

2021-08-06 16:38 UTC, anthonymartin commented on packages/app/components/Proposals/ProposalGrid.tsx
> +      const proposalStatus = (proposal as Proposal)?.status;
above line could look like `proposal: Proposal`

2021-08-06 16:38 UTC, anthonymartin commented on packages/contracts/scripts/deployWithValues.ts
> +const addressCidMap = {
should this be retrieved from `packages/contracts/scripts/addressCidMap.json` ?

2021-08-19 16:24 UTC, mefuru commented
Addresses #387 and and #389

2021-09-01 08:04 UTC, anthonymartin approved these changes

2021-09-02 10:21 UTC, merged