Develop emission db
popcorndao/workspace pull request #459
Opened 2021-09-09 15:47 UTC by mefuru

2021-09-10 09:18 UTC, anthonymartin requested changes

2021-09-10 09:18 UTC, anthonymartin commented on packages/emissions-dashboard/fixtures/saveFixturesToMongo.js
> +const uri = `mongodb+srv://${process.env.MONGO_USERNAME}:${process.env.MONGO_PASSWORD}@cluster0.mcgwt.mongodb.net`;
suggestion: replace entire uri with an environment variable so this isn't coupled to this mongo provider

2021-09-10 09:18 UTC, anthonymartin commented on packages/emissions-dashboard/netlify.toml
> +    PRIVATE_KEY = "31c18a7e6aaf93d1548ec9ae1b322c75400cb39627ae82bd1bb761ea79224a7d"
can you get rid of the stuff here that's irrelevant and from the other package?

2021-09-10 09:18 UTC, anthonymartin commented on packages/emissions-dashboard/netlify/functions/loadtransactions.ts
> +    const uri = 'mongodb://localhost:27017';
should this be localhost?

2021-09-10 09:18 UTC, anthonymartin commented on packages/emissions-dashboard/fixtures/saveFixturesToMongo.js
> +const MongoClient = require('mongodb').MongoClient;
we should only be using typescript files in our projects. is there a reason this one is js?

2021-09-10 09:19 UTC, anthonymartin commented
is there a readme? it would be nice to describe syncing data, bootstrapping the project, etc.

2021-09-10 10:52 UTC, anthonymartin commented
@mefuru we should also create a `.env.example` file that gets copied over to `.env` for env vars

2021-09-10 10:55 UTC, anthonymartin commented
the `.env.example` file should be created within this packages directory to keep the env localized to this package

2021-09-14 15:02 UTC, mefuru commented on packages/emissions-dashboard/fixtures/saveFixturesToMongo.js
> +const MongoClient = require('mongodb').MongoClient;
Just so I could test fixture grabs quickly. Updated to TS

2021-09-14 15:02 UTC, mefuru commented on packages/emissions-dashboard/netlify/functions/loadtransactions.ts
> +    const uri = 'mongodb://localhost:27017';
Updated to db uri in .env

2021-09-14 15:02 UTC, mefuru commented on packages/emissions-dashboard/netlify.toml
> +    PRIVATE_KEY = "31c18a7e6aaf93d1548ec9ae1b322c75400cb39627ae82bd1bb761ea79224a7d"
Done

2021-09-14 15:02 UTC, mefuru commented on packages/emissions-dashboard/fixtures/saveFixturesToMongo.js
> +const uri = `mongodb+srv://${process.env.MONGO_USERNAME}:${process.env.MONGO_PASSWORD}@cluster0.mcgwt.mongodb.net`;
Done

2022-08-15 17:18 UTC, closed without merging