Feature/28/amir lock pop
popcorndao/workspace pull request #57
Opened 2021-04-01 16:11 UTC by Amirjab21

Page that allows them to connect with wallet, and lock pop for a certain amount of time. The only thing not functional on this page is the button that lets them buy more POP - wasn't sure which contract to use for this.

2021-04-02 20:43 UTC, anthonymartin commented
@Amirjab21 can you resolve the conflicts in the PR?

2021-04-02 23:09 UTC, Amirjab21 commented
> @Amirjab21 can you resolve the conflicts in the PR?

done

2021-04-04 11:03 UTC, anthonymartin requested changes

2021-04-04 11:03 UTC, anthonymartin commented on packages/app/styles/globals.css
> +.lock-pop-title {
this project includes styled components and the tailwind css library. in the case of custom css, we should resort to using it with styled components, and only if tailwind css does not have the design elements required

2021-04-04 11:03 UTC, anthonymartin commented on packages/contracts/scripts/deployWithValues.js
> +// import { parseEther } from "@ethersproject/units";
can unused comments be removed?

2021-04-04 11:06 UTC, anthonymartin commented on packages/app/pages/lockPop.tsx
> +import Sidebar from '../containers/Grants/Sidebar/Sidebar';
there are a lot of unused variables on this page - is it possible to clean that up?

2021-04-04 11:09 UTC, anthonymartin commented on packages/app/pages/lockPop.tsx
> +    async function lockPop(amountToLock, amountOfTime = 606666) {
amountToLock is not used here

2021-04-04 14:09 UTC, anthonymartin commented
@Amirjab21 nice overall job. I've made some tweaks and polished up a few things. There were somethings that weren't functioning at all (like staking after approving an amount). Should be all good now, so I'll merge

2021-04-04 14:10 UTC, merged